[IDENTIFICATION]
# Set your user agent string here.
USERAGENT = KNKEVIN_CRAWLER

[CRAWLER]
# Starting urls to crawl.
SEEDURL = https://www.ics.uci.edu,https://www.cs.uci.edu,https://www.informatics.uci.edu,https://www.stat.uci.edu

# Allowable root domains.
ROOTDOMAINS = .ics.uci.edu,.cs.uci.edu,.informatics.uci.edu,.www.stat.uci.edu

# In seconds
POLITENESS = 0.5

[LOCAL PROPERTIES]
# Save file for progress.
SAVE = web_crawler/frontier.json